# Step 1: Build the app
FROM node:22-alpine AS builder

WORKDIR /app

RUN apk update && apk add --no-cache openssl

COPY app/package*.json ./
RUN npm install --force

ARG EMAIL_SERVER
ARG EMAIL_FROM
ARG DATABASE_URL
ARG FIREBASE_ADMIN_CREDENTIALS
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID

ENV EMAIL_SERVER=${EMAIL_SERVER}
ENV EMAIL_FROM=${EMAIL_FROM}
ENV DATABASE_URL=${DATABASE_URL}
ENV FIREBASE_ADMIN_CREDENTIALS=${FIREBASE_ADMIN_CREDENTIALS}
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_ID}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}

COPY app/ .
RUN npx prisma generate
RUN npm run build

# Step 2: Production image
FROM node:22-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/package*.json ./
RUN npm install --force --omit=dev

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.ts ./next.config.ts
COPY --from=builder /app/modules/common/database ./modules/common/database
COPY --from=builder /app/start.sh ./start.sh

CMD ["sh", "start.sh"]
